### ISSUE TITLE
loggy predicting  its own death 

### ISSUE THREAD

**Issue by aaronpoweruser** [koush/Loggy#1]
http://pastebin.com/ApNr6FAj 

anyway awesome idea, be looking for some pull request for tablet sms soon

**Comment by koush** [comment]
Yeah thats just what happens when you try to run process.destroy on a root process. The killing process spews that junk. I left a code comment about it. Loggy keeps running though:

``` java
try {
    kmsgProcess.destroy();
}
catch (Exception e)  {
    // destroy will cause some angry noise in logcat and throw, since
    // we are trying to destroy a root process.
    // the kill succeeds, but it still gets angry.
    // i assume it succeeds because the various streams are closed.
}
```
